// generated by Fast Light User Interface Designer (fluid) version 1.0402

#include "main.h"
#include "clsAppContext.h"
#include <FL/x.h>

static void cb_FLTK(Fl_Double_Window*, clsAppContext* v) {
  v->cbClose();
}

static void cb_NewText(Fl_Button*, clsAppContext* v) {
  v->cbAdd();
}

static void cb_Close(Fl_Button*, clsAppContext* v) {
  v->cbClose();
}

static void cb_Clear(Fl_Button*, clsAppContext* v) {
  v->cbNew();
}

static void cb_btn(Fl_ButtonOutput*, clsAppContext* v) {
  v->cbBtOutTest();
}

int main(int argc, char **argv) {
  Fl_Double_Window* w;
  clsAppContext AppContext;
  Fl::scheme("gtk+");
  { Fl_Double_Window* o = new Fl_Double_Window(481, 244, "FLTK window");
    w = o; (void)w;
    o->callback((Fl_Callback*)cb_FLTK, (void*)(&AppContext));
    o->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    { Fl_Button* o = new Fl_Button(143, 70, 100, 25, "NewText");
      o->callback((Fl_Callback*)cb_NewText, (void*)(&AppContext));
      AppContext.RegisterWg("btn_Test",o);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(360, 5, 100, 25, "Close");
      o->callback((Fl_Callback*)cb_Close, (void*)(&AppContext));
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(38, 70, 100, 25, "Clear");
      o->callback((Fl_Callback*)cb_Clear, (void*)(&AppContext));
      AppContext.RegisterWg("btn_New",o);
    } // Fl_Button* o
    { Fl_TextSpinner* o = new Fl_TextSpinner(93, 105, 135, 30, "Test");
      o->box(FL_NO_BOX);
      o->color(FL_BACKGROUND_COLOR);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(18);
      o->labelcolor(FL_FOREGROUND_COLOR);
      o->user_data((void*)(&AppContext));
      o->align(Fl_Align(FL_ALIGN_LEFT));
      o->when(FL_WHEN_RELEASE);
      AppContext.RegisterWg("txsp_Test",o);
      o->end();
    } // Fl_TextSpinner* o
    { Fl_Rotated_Label* o = new Fl_Rotated_Label(335, 100, 125, 27);
      o->box(FL_NO_BOX);
      o->color(FL_BACKGROUND_COLOR);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(18);
      o->labelcolor(FL_FOREGROUND_COLOR);
      o->user_data((void*)(&AppContext));
      o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
      o->when(FL_WHEN_RELEASE);
      AppContext.RegisterWg("rtl_YLax",o);
      o->text("Z.Im,Ω·cm²");
      o->angle(90);
    } // Fl_Rotated_Label* o
    { Fl_ButtonOutput* o = new Fl_ButtonOutput(79, 11, 135, 30, "btn");
      o->box(FL_NO_BOX);
      o->color(FL_DARK_YELLOW);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(18);
      o->labelcolor(FL_FOREGROUND_COLOR);
      o->callback((Fl_Callback*)cb_btn, (void*)(&AppContext));
      o->align(Fl_Align(FL_ALIGN_LEFT));
      o->when(FL_WHEN_RELEASE);
      AppContext.RegisterWg("btout_Test",o);
      o->button().label("@fileopen");
      o->button().color(fl_rgb_color(204,230,255));
      o->output().color(fl_rgb_color(204,230,255));
      o->end();
    } // Fl_ButtonOutput* o
    AppContext.Win(o);
    AppContext.init_windows();
    o->end();
  } // Fl_Double_Window* o
  w->icon((const void *)LoadIcon(fl_display, MAKEINTRESOURCE(501)));
  w->show(argc, argv);
  return Fl::run();
}
